DROP TABLE IF EXISTS director_title;
DROP TABLE IF EXISTS actor_title;
DROP TABLE if EXISTS title;
DROP TABLE if EXISTS director;
DROP TABLE if EXISTS actor;
DROP TABLE if EXISTS member;
DROP TABLE if EXISTS person;

CREATE SCHEMA if NOT EXISTS title;

CREATE TABLE director
(
    director_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(50) NOT NULL,
    surname    varchar(50) NOT NULL,
    birth_date date        NOT NULL,
    PRIMARY KEY (director_id)
);

CREATE TABLE actor
(
    actor_id  int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(50) NOT NULL,
    surname    varchar(50) NOT NULL,
    birth_date date        NOT NULL,
    PRIMARY KEY (actor_id)
);

CREATE TABLE actor_title
(
    actor_id int NOT NULL,
    title_id int NOT NULL,
    PRIMARY KEY (actor_id, title_id)
);

CREATE TABLE director_title
(
    director_id int NOT NULL,
    title_id    int NOT NULL,
    PRIMARY KEY (director_id, title_id)
);

CREATE TABLE title
(
    title_id      int         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name          varchar(50) NOT NULL,
    budget        real        NOT NULL,
    premiere_date date        NOT NULL,
    runtime       int         NOT NULL,
    box_office    real        NOT NULL,
    PRIMARY KEY (title_id)
);

CREATE TABLE member
(
    member_id  int         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    login    varchar(50) NOT NULL,
    password varchar(50) NOT NULL,
    PRIMARY KEY (member_id)
);

ALTER TABLE actor_title
    ADD FOREIGN KEY (actor_id) REFERENCES actor (actor_id)
        ON DELETE CASCADE;

ALTER TABLE actor_title
    ADD FOREIGN KEY (title_id) REFERENCES title (title_id)
        ON DELETE CASCADE;

ALTER TABLE director_title
    ADD FOREIGN KEY (director_id) REFERENCES director (director_id)
        ON DELETE CASCADE;

ALTER TABLE director_title
    ADD FOREIGN KEY (title_id) REFERENCES title (title_id)
        ON DELETE CASCADE;
